### ISSUE TITLE
The score is in percent right?

### ISSUE THREAD

**Issue by junaedifahmi** [kahne/fastwer#3]
Like when I have CER score of 89.6 it means 89.6 %,  and when I have CER like 0.6 it is 0.6% right?
Thank you

**Comment by kahne** [comment]
> Like when I have CER score of 89.6 it means 89.6 %, and when I have CER like 0.6 it is 0.6% right?
> Thank you

Yes, they are percentage numbers.

**Comment by junaedifahmi** [comment]
Okay, thank you. I was surprised because the first run I got really low cer. Thank you
